run:
  go: "1.22"
  timeout: 1m
  tests: false

linters:
  disable-all: false
  enable:
    - errcheck
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - usestdlibvars

linters-settings:
  gofumpt:
    extra-rules: true
  staticcheck:
    checks: ["all"]

